baseURL = 'https://cubatic45.github.io'
languageCode = 'en-us'
title = "cubatic's blog"

theme = "paper"


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  github = 'cubatic'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'cubatic'
  bio = 'enjoy life, enjoy coding'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://avatars.githubusercontent.com/u/148538725?v=4'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'
